// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkPkQAaZDrfvY5IQJR2jcN-vjRM626uRk',
    appId: '1:99347545874:web:82a35598678138a047bdcb',
    messagingSenderId: '99347545874',
    projectId: 'multi-store-bb623',
    authDomain: 'multi-store-bb623.firebaseapp.com',
    storageBucket: 'multi-store-bb623.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcxVuZZZq6Qb5HtmqzmdkWQXEuibIagjo',
    appId: '1:99347545874:android:b4da219ec4821f8647bdcb',
    messagingSenderId: '99347545874',
    projectId: 'multi-store-bb623',
    storageBucket: 'multi-store-bb623.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwoUPbudsrc70u71Q3KCJ_6c4_CupIwOU',
    appId: '1:99347545874:ios:ee41c4576e80fe3c47bdcb',
    messagingSenderId: '99347545874',
    projectId: 'multi-store-bb623',
    storageBucket: 'multi-store-bb623.appspot.com',
    iosClientId: '99347545874-cj39g7f0a49f1ujk55ivtl9kkfmnfmj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiVendor2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwoUPbudsrc70u71Q3KCJ_6c4_CupIwOU',
    appId: '1:99347545874:ios:79cfc010df47599c47bdcb',
    messagingSenderId: '99347545874',
    projectId: 'multi-store-bb623',
    storageBucket: 'multi-store-bb623.appspot.com',
    iosClientId: '99347545874-8hv939k52b76v2af7s79oq7l8dqtmbj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiVendor2.RunnerTests',
  );
}
